- src/main/kotlin/dsm/pick2024/domain/user/domain/User.kt
- src/main/kotlin/dsm/pick2024/domain/user/entity/UserJpaEntity.kt
- src/main/kotlin/dsm/pick2024/domain/user/entity/enums/Role.kt
- src/main/kotlin/dsm/pick2024/domain/user/mapper/UserMapper.kt
> 🔀 :: (PICK-9) add user table

- src/main/kotlin/dsm/pick2024/domain/admin/domain/Admin.kt
- src/main/kotlin/dsm/pick2024/domain/admin/entity/AdminJpaEntity.kt
- src/main/kotlin/dsm/pick2024/domain/admin/mapper/AdminMapper.kt
- src/main/kotlin/dsm/pick2024/domain/admin/persistence/repository/AdminRepository.kt
> 🔀 :: (PICK-10)add admin table

- src/main/kotlin/dsm/pick2024/domain/meal/domain/Meal.kt
- src/main/kotlin/dsm/pick2024/domain/meal/entity/MealJpaEntity.kt
- src/main/kotlin/dsm/pick2024/domain/meal/mapper/MealMapper.kt
- src/main/kotlin/dsm/pick2024/domain/meal/persistence/repository/MealRepository.kt
- src/main/kotlin/dsm/pick2024/domain/meal/port/in/.gitkeep
- src/main/kotlin/dsm/pick2024/domain/meal/presentation/.gitkeep
- src/main/kotlin/dsm/pick2024/domain/meal/presentation/dto/request/.gitkeep
- src/main/kotlin/dsm/pick2024/domain/meal/presentation/dto/response/.gitkeep
- src/main/kotlin/dsm/pick2024/domain/meal/service/.gitkeep
> 🔀 :: (PICK-11) 11 add meal table

- src/main/kotlin/dsm/pick2024/domain/notice/domain/Notice.kt
- src/main/kotlin/dsm/pick2024/domain/notice/entity/NoticeJpaEntity.kt
- src/main/kotlin/dsm/pick2024/domain/notice/mapper/NoticeMapper.kt
- src/main/kotlin/dsm/pick2024/domain/notice/persistence/repository/NoticeRepository.kt
- src/main/kotlin/dsm/pick2024/global/security/jwt/exception/ExpiredTokenException.kt
> 🔀 :: (PICK-13) add notice entity

- build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
- buildSrc/src/main/kotlin/DependencyVersions.kt
> 🔀 :: (PICK-19) querydsl setting

- src/main/kotlin/dsm/pick2024/domain/status/domain/Status.kt
- src/main/kotlin/dsm/pick2024/domain/status/entity/StatusJpaEntity.kt
- src/main/kotlin/dsm/pick2024/domain/status/entity/enum/StatusType.kt
- src/main/kotlin/dsm/pick2024/domain/status/mapper/StatusMapper.kt
- src/main/kotlin/dsm/pick2024/domain/status/persistence/repository/StatusRepository.kt
> 🔀 :: (PICK-17) add status entity

- src/main/kotlin/dsm/pick2024/domain/application/domain/Application.kt
- src/main/kotlin/dsm/pick2024/domain/application/entity/ApplicationJapEntity.kt
- src/main/kotlin/dsm/pick2024/domain/application/mapper/ApplicationMapper.kt
- src/main/kotlin/dsm/pick2024/domain/application/persistence/repository/ApplicationRepository.kt
> 🔀 :: (PICK-12) add application entity

- src/main/kotlin/dsm/pick2024/domain/application/domain/Application.kt
- src/main/kotlin/dsm/pick2024/domain/application/domain/EarlyReturn.kt
- src/main/kotlin/dsm/pick2024/domain/application/entity/ApplicationJapEntity.kt
- src/main/kotlin/dsm/pick2024/domain/application/entity/EarlyReturnJpaEntity.kt
- src/main/kotlin/dsm/pick2024/domain/application/enums/Status.kt
- src/main/kotlin/dsm/pick2024/domain/application/mapper/ApplicationMapper.kt
- src/main/kotlin/dsm/pick2024/domain/application/mapper/EarlyReturnMapper.kt
- src/main/kotlin/dsm/pick2024/domain/application/persistence/EarlyReturnPersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/application/persistence/repository/EarlyReturnRepository.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/in/CreateEarlyReturnUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/out/EarlyReturnPort.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/out/SaveEarlyReturnPort.kt
- src/main/kotlin/dsm/pick2024/domain/application/presentation/EarlyReturnController.kt
- src/main/kotlin/dsm/pick2024/domain/application/presentation/dto/request/CreateEarlyReturnRequest.kt
- src/main/kotlin/dsm/pick2024/domain/application/service/CreateEarlyReturnService.kt
> 🔀 :: (PICK-65) add 조기귀가신청 API

- src/main/kotlin/dsm/pick2024/domain/application/exception/AlreadyApplyingForPicnicException.kt
- src/main/kotlin/dsm/pick2024/domain/application/persistence/ApplicationPersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/application/persistence/repository/ApplicationRepository.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/in/ApplicationUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/out/ApplicationPort.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/out/ExistApplicationByUsernamePort.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/out/SaveApplicationPort.kt
- src/main/kotlin/dsm/pick2024/domain/application/presentation/ApplicationController.kt
- src/main/kotlin/dsm/pick2024/domain/application/presentation/dto/request/ApplicationRequest.kt
- src/main/kotlin/dsm/pick2024/domain/application/service/ApplicationService.kt
- src/main/kotlin/dsm/pick2024/global/error/exception/ErrorCode.kt
> 🔀 :: (PICK-29) add 외출신청 api

- Dockerfile
- src/main/kotlin/dsm/pick2024/domain/application/domain/Application.kt
- src/main/kotlin/dsm/pick2024/domain/application/entity/ApplicationJapEntity.kt
- src/main/kotlin/dsm/pick2024/domain/application/exception/ApplicationNotFoundException.kt
- src/main/kotlin/dsm/pick2024/domain/application/mapper/ApplicationMapper.kt
- src/main/kotlin/dsm/pick2024/domain/application/persistence/ApplicationPersistenceAdapterPort.kt
- src/main/kotlin/dsm/pick2024/domain/application/persistence/repository/ApplicationRepository.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/in/StatusApplicationUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/out/ApplicationPort.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/out/DeleteApplicationPort.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/out/FindApplicationByIdPort.kt
- src/main/kotlin/dsm/pick2024/domain/application/presentation/ApplicationController.kt
- src/main/kotlin/dsm/pick2024/domain/application/presentation/EarlyReturnController.kt
- src/main/kotlin/dsm/pick2024/domain/application/service/StatusApplicationService.kt
- src/main/kotlin/dsm/pick2024/global/error/exception/ErrorCode.kt
> 🔀 :: (PICK-69) add application status

- build.gradle.kts
- src/main/kotlin/dsm/pick2024/domain/selfstudy/persistence/SelfStudyPersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/port/in/QueryTodaySelfStudyTeacherUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/port/out/FindByTodaySelfStudyTeacherPort.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/port/out/SelfStudyPort.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/presentation/SelfStudyController.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/presentation/dto/response/QueryTodaySelfStudyTeacherResponse.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/service/QueryTodaySelfStudyTeacherService.kt
- src/main/kotlin/dsm/pick2024/global/config/querydsl/QueryDslConfig.kt
> 🔀 :: (PICK-36) add qeury now self study teacher

- build.gradle.kts
- src/main/kotlin/dsm/pick2024/domain/application/domain/Application.kt
- src/main/kotlin/dsm/pick2024/domain/application/domain/EarlyReturn.kt
- src/main/kotlin/dsm/pick2024/domain/application/entity/ApplicationJapEntity.kt
- src/main/kotlin/dsm/pick2024/domain/application/entity/EarlyReturnJpaEntity.kt
- src/main/kotlin/dsm/pick2024/domain/application/mapper/ApplicationMapper.kt
- src/main/kotlin/dsm/pick2024/domain/application/mapper/EarlyReturnMapper.kt
- src/main/kotlin/dsm/pick2024/domain/application/persistence/ApplicationPersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/application/persistence/ApplicationPersistenceAdapterPort.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/in/QueryClassApplicationUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/in/QueryFloorApplicationUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/out/ApplicationPort.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/out/QueryClassApplicationPort.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/out/QueryFloorApplicationPort.kt
- src/main/kotlin/dsm/pick2024/domain/application/presentation/ApplicationController.kt
- src/main/kotlin/dsm/pick2024/domain/application/presentation/dto/response/QueryApplicationResponse.kt
- src/main/kotlin/dsm/pick2024/domain/application/presentation/dto/response/QueryFloorApplicationResponse.kt
- src/main/kotlin/dsm/pick2024/domain/application/service/ApplicationService.kt
- src/main/kotlin/dsm/pick2024/domain/application/service/CreateEarlyReturnService.kt
- src/main/kotlin/dsm/pick2024/domain/application/service/QueryClassApplicationService.kt
- src/main/kotlin/dsm/pick2024/domain/application/service/QueryFloorApplicationService.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/persistence/SelfStudyPersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/port/in/QueryTodaySelfStudyTeacherUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/port/out/FindByTodaySelfStudyTeacherPort.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/port/out/SelfStudyPort.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/presentation/SelfStudyController.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/presentation/dto/response/QueryTodaySelfStudyTeacherResponse.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/service/QueryTodaySelfStudyTeacherService.kt
- src/main/kotlin/dsm/pick2024/global/config/querydsl/QueryDslConfig.kt
> 🔀 :: (PICK-34)add query application

- src/main/kotlin/dsm/pick2024/domain/admin/mapper/AdminMapper.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/domain/Classroom.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/entity/ClassroomJpaEntity.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/mapper/ClassroomMapper.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/persistence/ClassroomPersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/port/in/QueryFloorClassroomUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/port/in/QueryGradeClassroomUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/port/out/ClassroomPort.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/port/out/QueryFloorClassroomPort.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/port/out/QueryGradeClassroomPort.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/presentation/ClassroomController.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/presentation/dto/response/QueryClassroomResponse.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/presentation/dto/response/QueryFloorClassroomResponse.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/service/QueryFloorClassroomService.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/service/QueryGradeClassroomService.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/service/UserMoveClassroomService.kt
- src/main/kotlin/dsm/pick2024/domain/meal/mapper/MealMapper.kt
- src/main/kotlin/dsm/pick2024/domain/notice/mapper/NoticeMapper.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/mapper/SelfStudyMapper.kt
- src/main/kotlin/dsm/pick2024/domain/user/mapper/UserMapper.kt
- src/main/kotlin/dsm/pick2024/global/base/GenericMapper.kt
> 🔀 :: (PICK-75)add query classroom move

- src/main/kotlin/dsm/pick2024/domain/application/persistence/ApplicationPersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/application/persistence/EarlyReturnPersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/application/persistence/repository/ApplicationRepository.kt
- src/main/kotlin/dsm/pick2024/domain/application/persistence/repository/EarlyReturnRepository.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/in/StatusNOApplicationUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/in/StatusNOEarlyReturnUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/out/ApplicationPort.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/out/DeleteAllApplicationPort.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/out/DeleteAllEarlyReturnPort.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/out/EarlyReturnPort.kt
- src/main/kotlin/dsm/pick2024/domain/application/presentation/ApplicationController.kt
- src/main/kotlin/dsm/pick2024/domain/application/presentation/EarlyReturnController.kt
- src/main/kotlin/dsm/pick2024/domain/application/service/StatusNOApplicationService.kt
- src/main/kotlin/dsm/pick2024/domain/application/service/StatusNOEarlyReturnService.kt
- src/main/kotlin/dsm/pick2024/domain/application/service/StatusOKApplicationService.kt
- src/main/kotlin/dsm/pick2024/domain/application/service/StatusOKEarlyReturnService.kt
> 🔀 :: (PICK-82) add application earlyreturn no

- src/main/kotlin/dsm/pick2024/domain/application/persistence/EarlyReturnPersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/in/QueryClassEarlyReturnUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/in/QueryFloorEarlyReturnUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/out/EarlyReturnPort.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/out/QueryClassEarlyReturnPort.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/out/QueryFloorEarlyReturnPort.kt
- src/main/kotlin/dsm/pick2024/domain/application/presentation/ApplicationController.kt
- src/main/kotlin/dsm/pick2024/domain/application/presentation/EarlyReturnController.kt
- src/main/kotlin/dsm/pick2024/domain/application/presentation/dto/response/QueryEarlyReturnResponse.kt
- src/main/kotlin/dsm/pick2024/domain/application/service/QueryClassEarlyReturnService.kt
- src/main/kotlin/dsm/pick2024/domain/application/service/QueryFloorEarlyReturnService.kt
> 🔀 :: (PICK-85) add query early return

- src/main/kotlin/dsm/pick2024/domain/application/domain/WeekendMeal.kt
- src/main/kotlin/dsm/pick2024/domain/application/entity/WeekendMealJpaEntity.kt
- src/main/kotlin/dsm/pick2024/domain/application/exception/WeekendMealNotFoundException.kt
- src/main/kotlin/dsm/pick2024/domain/application/mapper/WeekendMealMapper.kt
- src/main/kotlin/dsm/pick2024/domain/application/persistence/WeekendMealPersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/application/persistence/repository/WeekendMealRepository.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/in/CreateWeekendMealUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/out/FindWeekendMealByUserIdPort.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/out/FindWeekendMealByUserNamePort.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/out/SaveWeekendMealPort.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/out/WeekendMealPort.kt
- src/main/kotlin/dsm/pick2024/domain/application/presentation/WeekendMealController.kt
- src/main/kotlin/dsm/pick2024/domain/application/service/WeekendMealService.kt
- src/main/kotlin/dsm/pick2024/global/error/exception/ErrorCode.kt
> 🔀 :: (PICK-31) add weekend meal application

- src/main/kotlin/dsm/pick2024/domain/application/port/in/QueryAllOKApplicationUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/application/presentation/ApplicationController.kt
- src/main/kotlin/dsm/pick2024/domain/application/service/QueryAllNonReturnApplicationService.kt
- src/main/kotlin/dsm/pick2024/domain/application/service/QueryAllOKApplicationService.kt
- src/main/kotlin/dsm/pick2024/domain/earlyreturn/presentation/EarlyReturnController.kt
- src/main/kotlin/dsm/pick2024/domain/earlyreturn/service/QueryAllOKEarlyReturnService.kt
> 🔀 :: (PICK-97) add query application

- build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
- buildSrc/src/main/kotlin/DependencyVersions.kt
- src/main/kotlin/dsm/pick2024/domain/meal/domain/Meal.kt
- src/main/kotlin/dsm/pick2024/domain/meal/entity/MealJpaEntity.kt
- src/main/kotlin/dsm/pick2024/domain/meal/persistence/MealPersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/meal/persistence/repository/MealRepository.kt
- src/main/kotlin/dsm/pick2024/domain/meal/port/out/FindMealsByMealDatePort.kt
- src/main/kotlin/dsm/pick2024/domain/meal/port/out/MealPort.kt
- src/main/kotlin/dsm/pick2024/domain/meal/port/out/SaveMealPort.kt
- src/main/kotlin/dsm/pick2024/domain/meal/presentation/.gitkeep
- src/main/kotlin/dsm/pick2024/domain/meal/presentation/dto/MealController.kt
- src/main/kotlin/dsm/pick2024/domain/meal/presentation/dto/response/.gitkeep
- src/main/kotlin/dsm/pick2024/domain/meal/presentation/dto/response/MealListResponse.kt
- src/main/kotlin/dsm/pick2024/domain/meal/service/.gitkeep
- src/main/kotlin/dsm/pick2024/domain/meal/service/MealResponseService.kt
- src/main/kotlin/dsm/pick2024/domain/meal/service/MealService.kt
- src/main/kotlin/dsm/pick2024/infrastructure/feign/NeisMealFeignClientService.kt
- src/main/kotlin/dsm/pick2024/infrastructure/feign/client/NeisFeignClient.kt
- src/main/kotlin/dsm/pick2024/infrastructure/feign/client/property/NeisFeignProperty.kt
- src/main/kotlin/dsm/pick2024/infrastructure/feign/client/response/NeisFeignClientMealServiceDietInfoResponse.kt
- src/main/resources/application.yaml
> 🔀 :: (PICK-103) save meal data

- src/main/kotlin/dsm/pick2024/domain/application/port/in/QueryStatusApplicationUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/application/presentation/ApplicationController.kt
- src/main/kotlin/dsm/pick2024/domain/application/presentation/dto/response/QueryStatusApplicationResponse.kt
- src/main/kotlin/dsm/pick2024/domain/application/service/QueryStatusApplicationService.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/persistence/ClassroomPersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/port/out/ClassroomPort.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/port/out/QueryAllClassroomPort.kt
> feat(application): status상태 관리 API 추가

- build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
- buildSrc/src/main/kotlin/DependencyVersions.kt
- src/main/kotlin/dsm/pick2024/domain/weekendmeal/persistence/WeekendMealPersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/weekendmeal/persistence/repository/WeekendMealRepository.kt
- src/main/kotlin/dsm/pick2024/domain/weekendmeal/port/out/FindWeekendMealByStatus.kt
- src/main/kotlin/dsm/pick2024/domain/weekendmeal/port/out/WeekendMealPort.kt
- src/main/kotlin/dsm/pick2024/domain/weekendmeal/presentation/WeekendMealController.kt
- src/main/kotlin/dsm/pick2024/domain/weekendmeal/service/WeekendMealExcelService.kt
> 🔀 :: (PICK-30)weekend meal back office

- src/main/kotlin/dsm/pick2024/domain/classroom/domain/Classroom.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/entity/ClassroomJpaEntity.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/exception/ClassroomNorFoundException.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/mapper/ClassroomMapper.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/persistence/ClassroomPersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/persistence/repository/ClassroomRepository.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/port/in/ChangeClassroomStatusUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/port/out/ClassroomPort.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/port/out/ExistOKByUserIdPort.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/port/out/FindOKClassroomPort.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/port/out/SaveAllClassroomPort.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/presentation/ClassroomController.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/presentation/dto/request/ClassroomStatusRequest.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/presentation/dto/request/UserMoveClassroomRequest.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/presentation/dto/response/QueryClassroomResponse.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/presentation/dto/response/QueryMainUserMoveClassroomResponse.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/presentation/dto/response/UserMoveClassroomResponse.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/service/ChangeClassroomStatusService.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/service/QueryFloorClassroomService.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/service/QueryGradeClassroomService.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/service/UserMoveClassroomQueryService.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/service/UserMoveClassroomService.kt
- src/main/kotlin/dsm/pick2024/domain/main/MainService.kt
- src/main/kotlin/dsm/pick2024/global/config/security/SecurityConfig.kt
- src/main/kotlin/dsm/pick2024/global/error/exception/ErrorCode.kt
> 🔀 :: (PICK-109)classroom accept

- src/main/kotlin/dsm/pick2024/domain/selfstudy/port/in/RegistrationSelfStudyTeacherUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/presentation/SelfStudyController.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/service/RegistrationSelfStudyTeacherService.kt
> 🔀 :: (PICK-115) bug modify selfstudy

- src/main/kotlin/dsm/pick2024/domain/application/service/ApplicationService.kt
- src/main/kotlin/dsm/pick2024/domain/status/persistence/StatusPersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/status/port/in/ChangeStatusUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/status/port/in/QueryClassStatusUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/status/port/out/SaveAllStatusPort.kt
- src/main/kotlin/dsm/pick2024/domain/status/present/dto/request/ChangeStatusRequest.kt
- src/main/kotlin/dsm/pick2024/domain/status/presentation/StatusController.kt
- src/main/kotlin/dsm/pick2024/domain/status/presentation/dto/request/ChangeStatusRequest.kt
- src/main/kotlin/dsm/pick2024/domain/status/presentation/dto/response/QueryClassStatusResponse.kt
- src/main/kotlin/dsm/pick2024/domain/status/service/ChangeStatusService.kt
- src/main/kotlin/dsm/pick2024/domain/status/service/QueryClassStatusService.kt
- src/main/kotlin/dsm/pick2024/domain/status/service/SaveAllStatusUserService.kt
> 🔀 :: (PICK-117) modify admin api

- src/main/kotlin/dsm/pick2024/domain/afterschool/service/SaveAfterSchoolStudentService.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/service/SelfStudyTeacherService.kt
> 🔀 :: (PICK-122)bug selfstudy register modify

- src/main/kotlin/dsm/pick2024/domain/afterschool/service/SaveAfterSchoolStudentService.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/domain/Attendance.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/entity/AttendanceJpaEntity.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/mapper/AttendanceMapper.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/persistence/AttendancePersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/persistence/repository/AttendanceJpaRepository.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/persistence/repository/AttendanceRepository.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/port/in/ChangeAttendanceUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/port/in/SaveAllAttendanceUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/port/out/AttendancePort.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/port/out/FindByUserIdPort.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/port/out/SaveAll.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/presentation/AttendanceController.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/presentation/dto/request/ChangeAttendanceRequest.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/service/ChangeAttendanceService.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/service/SaveAllAttendanceSaveAllUserService.kt
- src/main/kotlin/dsm/pick2024/infrastructure/feign/client/response/XquareResponse.kt
- src/main/kotlin/dsm/pick2024/infrastructure/feign/client/response/XquareUserAllResponse.kt
> 🔀 :: (PICK-52)Add attendance

- src/main/kotlin/dsm/pick2024/domain/attendance/domain/Attendance.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/mapper/AttendanceMapper.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/persistence/AttendancePersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/port/in/QueryClassAttendanceUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/port/out/AttendancePort.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/port/out/QueryClassAttendancePort.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/presentation/AttendanceController.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/presentation/dto/response/QueryAttendanceResponse.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/service/QueryClassAttendanceService.kt
> 🔀 :: (PICK-128)query class attendance

- src/main/kotlin/dsm/pick2024/domain/afterschool/persistence/AfterSchoolStudentPersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/afterschool/persistence/repository/AfterSchoolStudentRepository.kt
- src/main/kotlin/dsm/pick2024/domain/afterschool/port/out/AfterSchoolStudentPortUser.kt
- src/main/kotlin/dsm/pick2024/domain/afterschool/port/out/DeleteAllSchoolStudentPort.kt
- src/main/kotlin/dsm/pick2024/domain/status/persistence/StatusPersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/status/persistence/repository/StatusRepository.kt
- src/main/kotlin/dsm/pick2024/domain/status/port/in/ResetStatusUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/status/port/out/FindAllStatusPort.kt
- src/main/kotlin/dsm/pick2024/domain/status/port/out/StatusPort.kt
- src/main/kotlin/dsm/pick2024/domain/status/service/ResetStatusService.kt
- src/main/kotlin/dsm/pick2024/infrastructure/schedule/ScheduleService.kt
> 🔀 :: (PICK-139)add reset status after school

- src/main/kotlin/dsm/pick2024/domain/selfstudy/port/in/SelfStudyTeacherUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/presentation/SelfStudyController.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/service/SelfStudyTeacherService.kt
> 🔀 :: (PICK-146)delete selfstudy api

- src/main/kotlin/dsm/pick2024/domain/selfstudy/persistence/SelfStudyPersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/persistence/repository/SelfStudyRepository.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/port/out/DeleteByDatePort.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/port/out/SelfStudyPort.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/service/SelfStudyTeacherService.kt
> 🔀 :: (PICK-149)modify regist selfstudy

- src/main/kotlin/dsm/pick2024/domain/attendance/port/out/AttendancePort.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/port/out/FindAttendanceByUserIdPort.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/service/ChangeAttendanceService.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/service/ChangeClassroomStatusService.kt
- src/main/kotlin/dsm/pick2024/domain/meal/service/SaveMealService.kt
> 🔀 :: (PICK-151)classroom auto status change

- src/main/kotlin/dsm/pick2024/domain/admin/domain/Admin.kt
- src/main/kotlin/dsm/pick2024/domain/afterschool/domain/AfterSchoolStudent.kt
- src/main/kotlin/dsm/pick2024/domain/application/domain/Application.kt
- src/main/kotlin/dsm/pick2024/domain/applicationstory/domain/ApplicationStory.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/domain/Attendance.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/domain/Classroom.kt
- src/main/kotlin/dsm/pick2024/domain/earlyreturn/domain/EarlyReturn.kt
- src/main/kotlin/dsm/pick2024/domain/meal/domain/Meal.kt
- src/main/kotlin/dsm/pick2024/domain/notice/domain/Notice.kt
- src/main/kotlin/dsm/pick2024/domain/schedule/domain/Schedule.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/domain/SelfStudy.kt
- src/main/kotlin/dsm/pick2024/domain/status/domain/Status.kt
- src/main/kotlin/dsm/pick2024/domain/timetable/domain/Timetable.kt
- src/main/kotlin/dsm/pick2024/domain/user/domain/User.kt
- src/main/kotlin/dsm/pick2024/domain/weekendmeal/domain/WeekendMeal.kt
- src/main/kotlin/dsm/pick2024/global/annotation/Aggregate.kt
- src/main/kotlin/dsm/pick2024/global/annotation/ReadOnlyUseCase.kt
- src/main/kotlin/dsm/pick2024/global/annotation/UseCase.kt
> Add annotation

- src/main/kotlin/dsm/pick2024/domain/status/presentation/dto/response/QueryClassStatusResponse.kt
- src/main/kotlin/dsm/pick2024/domain/status/service/QueryClassStatusService.kt
> 🔀 :: (PICK-163)change class status response

- src/main/kotlin/dsm/pick2024/domain/attendance/presentation/dto/response/QueryAttendanceResponse.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/service/QueryClassAttendanceService.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/service/QueryClubAttendanceService.kt
- src/main/kotlin/dsm/pick2024/domain/status/presentation/dto/response/QueryClassStatusResponse.kt
- src/main/kotlin/dsm/pick2024/domain/status/service/QueryClassStatusService.kt
> 🔀 :: (PICK-165)change attendance response

- src/main/kotlin/dsm/pick2024/domain/attendance/service/QueryClassAttendanceService.kt
> 🔀 :: (PICK-171)modify-search-move-calssroom-bug

- src/main/kotlin/dsm/pick2024/domain/weekendmeal/persistence/WeekendMealPersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/weekendmeal/port/out/SaveAllWeekendMealPort.kt
- src/main/kotlin/dsm/pick2024/domain/weekendmeal/service/ResetWeekendMealService.kt
- src/main/kotlin/dsm/pick2024/domain/weekendmeal/service/SaveAllWeekendMealUserMealService.kt
> 🔀 :: (PICK-173)dsave all weekend meal user meal service refactor

- src/main/kotlin/dsm/pick2024/global/config/security/SecurityConfig.kt
- src/main/kotlin/dsm/pick2024/global/error/GlobalExceptionHandler.kt
> security error 해결

- src/main/kotlin/dsm/pick2024/domain/applicationstory/service/QueryClassUserService.kt
> 🔀 :: (PICK-178)modify wrong import

- src/main/kotlin/dsm/pick2024/domain/applicationstory/persistence/ApplicationStoryPersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/applicationstory/persistence/repository/ApplicationStoryRepository.kt
- src/main/kotlin/dsm/pick2024/domain/earlyreturn/service/QueryMyEarlyReturnService.kt
> 🔀 :: (PICK-180)modify :: findByUserIdOrderByDateDesc

- build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
- src/main/kotlin/dsm/pick2024/Pick2024ServerApplication.kt
- src/main/kotlin/dsm/pick2024/domain/meal/service/QueryDayMealService.kt
- src/main/kotlin/dsm/pick2024/domain/timetable/service/QueryTimetableService.kt
- src/main/kotlin/dsm/pick2024/domain/timetable/service/QueryWeekTimetableService.kt
- src/main/kotlin/dsm/pick2024/global/config/cache/CacheConfig.kt
- src/main/kotlin/dsm/pick2024/infrastructure/schedule/ScheduleService.kt
- src/main/resources/application.yaml
> 🔀 :: (PICK-170)caching

- src/main/kotlin/dsm/pick2024/domain/meal/service/QueryDayMealService.kt
- src/main/kotlin/dsm/pick2024/infrastructure/schedule/ScheduleService.kt
> 🔀 :: (PICK-185)meal caching error

- src/main/kotlin/dsm/pick2024/domain/timetable/service/QueryTimetableService.kt
- src/main/kotlin/dsm/pick2024/domain/timetable/service/QueryWeekTimetableService.kt
- src/main/kotlin/dsm/pick2024/infrastructure/schedule/ScheduleService.kt
> 🔀 :: (PICK-187)modify :: timetable caching commenting

- src/main/kotlin/dsm/pick2024/domain/timetable/service/QueryWeekTimetableService.kt
> QueryWeekTimetableService 로직변경

- src/main/kotlin/dsm/pick2024/domain/application/persistence/ApplicationPersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/application/service/QueryAllNonReturnApplicationService.kt
- src/main/kotlin/dsm/pick2024/domain/earlyreturn/persistence/EarlyReturnPersistenceAdapter.kt
>  🔀 :: (PICK-190)modify :: findAll sortedWith

- src/main/kotlin/dsm/pick2024/domain/attendance/port/out/QueryAttendancePort.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/service/QueryClubAttendanceService.kt
> Attendance error

- src/main/kotlin/dsm/pick2024/domain/application/port/in/StatusApplicationChangeUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/application/presentation/ApplicationController.kt
- src/main/kotlin/dsm/pick2024/domain/application/service/StatusApplicationChangeService.kt
> 🔀 :: (PICK-203)multiple application return

- src/main/kotlin/dsm/pick2024/domain/admin/persistence/AdminPersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/admin/persistence/repository/AdminRepository.kt
- src/main/kotlin/dsm/pick2024/domain/admin/port/out/ExistsByAdminIdPort.kt
- src/main/kotlin/dsm/pick2024/domain/admin/port/out/QueryAdminPort.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/exception/TeacherNotFoundException.kt
- src/main/kotlin/dsm/pick2024/domain/selfstudy/service/SelfStudyTeacherService.kt
- src/main/kotlin/dsm/pick2024/global/error/exception/ErrorCode.kt
> 🔀 :: (PICK-205)selfstudy exception handling

- src/main/kotlin/dsm/pick2024/domain/afterschool/persistence/AfterSchoolStudentPersistenceAdapterStudent.kt
- src/main/kotlin/dsm/pick2024/domain/afterschool/persistence/repository/AfterSchoolStudentRepository.kt
> 🔀 :: (PICK-207)modify :: deleteByUserId -> deleteById

- src/main/kotlin/dsm/pick2024/domain/earlyreturn/service/QueryAllOKEarlyReturnService.kt
- src/main/kotlin/dsm/pick2024/domain/earlyreturn/service/QueryAllReasonEarlyReturnService.kt
> 🔀 :: (PICK-210)add :: sorted

- src/main/kotlin/dsm/pick2024/domain/weekendmeal/persistence/WeekendMealPersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/weekendmeal/presentation/WeekendMealController.kt
- src/main/kotlin/dsm/pick2024/domain/weekendmeal/service/QueryAllWeekendMealStatus.kt
> 🔀 :: (PiCK-212)refactor :: userId -> id

- src/main/kotlin/dsm/pick2024/domain/attendance/persistence/AttendancePersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/persistence/repository/AttendanceRepository.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/port/out/QueryAttendancePort.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/service/QueryClassAttendanceService.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/service/QueryClubAttendanceService.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/persistence/PersistenceAdapterClassRoom.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/port/out/QueryClassroomPort.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/service/QueryFloorClassroomService.kt
- src/main/kotlin/dsm/pick2024/domain/classroom/service/QueryGradeClassroomService.kt
close #214 
요일 화요일 설정 시
이외 설정 시
> 🔀 :: (PICK-214)classroom startplace error

- src/main/kotlin/dsm/pick2024/domain/classroom/service/QueryFloorClassroomService.kt
> 🔀 :: (PICK-216)modify :: floor5 logic

- src/main/kotlin/dsm/pick2024/domain/admin/service/AdminLoginService.kt
- src/main/kotlin/dsm/pick2024/domain/user/service/UserLoginService.kt
- src/main/kotlin/dsm/pick2024/infrastructure/feign/client/XquareFeignClient.kt
- src/main/kotlin/dsm/pick2024/infrastructure/feign/client/dto/request/XquareRequest.kt
> modify :: logic

- src/main/kotlin/dsm/pick2024/domain/schedule/persistence/SchedulePersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/schedule/persistence/repository/ScheduleRepository.kt
- src/main/kotlin/dsm/pick2024/domain/schedule/port/in/QueryDateScheduleUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/schedule/port/out/QuerySchedulePort.kt
- src/main/kotlin/dsm/pick2024/domain/schedule/service/QueryDateScheduleService.kt
> 🔀 :: (PICK-221)many schedule error

- src/main/kotlin/dsm/pick2024/domain/application/persistence/ApplicationPersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/application/persistence/repository/ApplicationRepository.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/in/QueryFloorAndStatusApplicationUseCase.kt.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/in/QueryFloorApplicationUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/application/port/out/QueryApplicationPort.kt
- src/main/kotlin/dsm/pick2024/domain/application/presentation/ApplicationController.kt
- src/main/kotlin/dsm/pick2024/domain/application/service/QueryFloorApplicationService.kt
> 🔀 :: (PICK-224)query floor application student

- src/main/kotlin/dsm/pick2024/domain/application/persistence/ApplicationPersistenceAdapter.kt
- src/main/kotlin/dsm/pick2024/domain/attendance/service/QueryClubAttendanceService.kt
> 🔀 :: (PICK-226)modify :: findBy -> findOKClassroom

- src/main/kotlin/dsm/pick2024/domain/applicationstory/port/in/QueryAllUserApplicationStoryUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/applicationstory/presentation/ApplicationStoryController.kt
- src/main/kotlin/dsm/pick2024/domain/applicationstory/service/QueryAllUserApplicationStoryService.kt
- src/main/kotlin/dsm/pick2024/domain/applicationstory/service/QueryClassUserService.kt
- src/main/kotlin/dsm/pick2024/domain/applicationstory/service/QueryUserApplicationStoryService.kt
> 🔀 :: (PICK-230)query all applicationStory

- src/main/kotlin/dsm/pick2024/domain/application/service/QueryMyApplicationService.kt
- src/main/kotlin/dsm/pick2024/domain/earlyreturn/service/QueryMyEarlyReturnService.kt
- src/main/kotlin/dsm/pick2024/domain/main/MainService.kt
> 🔀 :: (PiCK-338) time foramt

- src/main/kotlin/dsm/pick2024/domain/timetable/port/in/QueryTeacherTimetableUseCase.kt
- src/main/kotlin/dsm/pick2024/domain/timetable/presentation/TimetableController.kt
- src/main/kotlin/dsm/pick2024/domain/timetable/presentation/dto/request/QueryTeacherTimetableRequest.kt
- src/main/kotlin/dsm/pick2024/domain/timetable/service/QueryTeacherTimetableService.kt
> 🔀 :: (PiCK-377) timetable all refactoring
